<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Kondongpu.Domain</RootNamespace>
    <AssemblyName>Kondongpu.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Entities\PatientCompany.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\*.resx">
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\" />
  </ItemGroup>


</Project>
