/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'dashboards': RouteRecordInfo<'dashboards', '/dashboards', Record<never, never>, Record<never, never>>,
    'signin-oidc': RouteRecordInfo<'signin-oidc', '/signin-oidc', Record<never, never>, Record<never, never>>,
    'signout': RouteRecordInfo<'signout', '/signout', Record<never, never>, Record<never, never>>,
    'signout-callback-oidc': RouteRecordInfo<'signout-callback-oidc', '/signout-callback-oidc', Record<never, never>, Record<never, never>>,
    'silent-renew': RouteRecordInfo<'silent-renew', '/silent-renew', Record<never, never>, Record<never, never>>,
  }
}
